### ISSUE TITLE
QUIC

### ISSUE THREAD

**Issue by martinthomson** [dadrian/tldr.fail#6]
It might be worth adding something about QUIC to your Q&A.  In QUIC, we took steps to avoid this problem, but it is perhaps more relevant there.

**Comment by davidben** [comment]
Well, we took steps in that we didn't make the *protocol* assume a single-packet ClientHello. 😄 We didn't take that step in TCP only because it was already there. I'm not aware of anything *ensuring* that servers accepted multi-packet ClientHellos.

I think QUIC is mostly saved from our attention by a combination of:
* QUIC is much newer so there's less long of a tail of buggy endpoints and middleware to worry about
* QUIC is typically deployed with a TCP fallback/race, so intolerance would look like a TCP fallback and be "fine"
